[package]
name= "p5-rs-st"
# name = "{{project-name}}"
version = "0.1.0"
authors = ["m"]
# authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
p5-sys = "0.1"
wasm-bindgen = "0.2.67"
