[package]
name = "{{project}}"
version = "0.1.0"
authors = ["{{author}}"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
p5-sys = { git = "https://github.com/Maan2003/p5-rs" }
wasm-bindgen = "0.2.67"
